version: 2.1
orbs:
    aws-s3: circleci/aws-s3@1.0.0
jobs:
    build:
        docker:
          - image: 'opensuse:leap'
        steps:
          - run: 'zypper install -y --type pattern devel_basis devel_C_C++'
          - run: 'zypper install -y git python3-devel python-devel gcc-c++ unzip'
          - checkout
          - run:
              command: ./build/build.sh
              no_output_timeout: 90m
          - persist_to_workspace:
              root: .
              paths: rtems-install
    deploy:
        docker:
          - image: 'opensuse:leap'
        steps:
          - run: 'zypper install -y aws-cli'
          - attach_workspace:
              at: /tmp/rtems-install
          - run: 'GRISP_TOOLCHAIN_REVISION=$(cat /tmp/rtems-install/rtems/5/GRISP_TOOLCHAIN_REVISION)'
          - run:
              name: Create archive
              command: tar -czf rtems-install-$GRISP_TOOLCHAIN_REVISION.tar.gz .
              working_directory: /tmp/rtems-install
          - deploy:
              command: aws s3 cp rtems-install-*.tar.gz s3://grisp/platforms/grisp_base/toolchain/a

workflows:
    version: 2
    build-deploy:
        jobs:
          - build
          - deploy:
              requires:
                - build
