version: 2.1
orbs:
    aws-s3: circleci/aws-s3@1.0.0
jobs:
    build:
        docker:
          - image: 'opensuse:leap'
        steps:
          - run: 'zypper install -y --type pattern devel_basis devel_C_C++'
          - run: 'zypper install -y git python3-devel python-devel gcc-c++ unzip'
          - checkout
          - run: 'git submodule update --init rtems-source-builder'
          - run:
              name: Disable parallelism during gcc build due to RAM limit at CircleCI
              command: 'sed -i "s/%define with_threads 1/%define with_threads 0/" rtems-source-builder/rtems/config/tools/rtems-gcc-7.3.0-newlib-3.0.0.cfg'
          - run:
              command: ./build/build.sh
              no_output_timeout: 90m
          - persist_to_workspace:
              root: .
              paths: rtems-install
    deploy:
        docker:
          - image: 'opensuse:leap'
        steps:
          - run: 'zypper install -y aws-cli tar gzip'
          - attach_workspace:
              at: /tmp
          - run: 'GRISP_TOOLCHAIN_REVISION=$(cat /tmp/rtems-install/rtems/5/GRISP_TOOLCHAIN_REVISION)'
          - run:
              name: Create archive
              command: tar -czf /tmp/grisp_toolchain_arm-rtems5_Linux_$GRISP_TOOLCHAIN_REVISION.tar.gz .
              working_directory: /tmp/rtems-install
          - deploy:
              command: aws s3 cp /tmp/grisp_toolchain_*.tar.gz s3://grisp/platforms/grisp_base/toolchain/
workflows:
    version: 2
    build-deploy:
        jobs:
          - build
          - deploy:
              requires:
                - build
